language: node_js
node_js: '8'
install:
  - npm install
jobs:
  include:
    - stage: Build Gatsby Website
      script: npm run build
      deploy:
        provider: script
        script: npm run deploy
        skip_cleanup: true
        on:
          branch: master
